name: Go Build Example

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/15 * * * 1-6'  # A cada 15 minutos, de segunda a sábado

env:
  FILE_NAME: hello-server

jobs:
  build-go:
    runs-on: ubuntu-latest

    steps:
      # Checkout o código na branch main
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step para build no Linux
      - name: Build Go for Linux
        run: go build ${{ env.FILE_NAME }}.go

      # Upload artifact for Linux
      - name: Upload artifact for Linux
        uses: actions/upload-artifact@v4.0.0
        with:
          name: linux
          path: ./${{ env.FILE_NAME }}

      # Step para build no Windows
      - name: Build Go for Windows
        run: |
          GOOS=windows GOARCH=amd64 go build ${{ env.FILE_NAME }}.go

      # Upload artifact for Windows
      - name: Upload artifact for Windows
        uses: actions/upload-artifact@v4.0.0
        with:
          name: windows
          path: ./${{ env.FILE_NAME }}.exe

  download-and-run-linux:
    needs: build-go  # Dependência do job build-go
    runs-on: ubuntu-latest

    steps:
      # Checkout o código no repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # Baixar o artefato gerado no job build-go (Linux)
      - name: Download Linux artifact
        uses: actions/download-artifact@v4.0.0
        with:
          name: linux

      # Executar o comando no Linux para ler as opções do script run.sh
      - name: Run script
        run: source ./run.sh

  download-only-windows:
    needs: build-go  # Dependência do job build-go
    runs-on: windows-latest

    steps:
      # Checkout o código no repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # Baixar o artefato gerado no job build-go (Windows)
      - name: Download Windows artifact
        uses: actions/download-artifact@v4.0.0
        with:
          name: windows
